server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /Tamagotchi.pbw {
        default_type application/octet-stream;
        add_header Content-Disposition 'attachment; filename="Tamagotchi.pbw"';
    }
}
